language: python

python:
  - "2.7"
  - "3.8"

# Install the codecov pip dependency
install:
  - pip install codecov

# command to run tests
script: coverage run -m pytest

after_success:
  - codecov
